# -*- coding: utf-8 -*-
"""Calender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_L3i_e4JVSt2d2fRNui0MaWgBMfOEYqZ
"""



global n_l
n_l=0
def number_leap(year):
  global n_l
  if year%4==0:
    if year%100!=0:
      n_l+=1
    else:
      if year%400==0:
        n_l+=1
      # else:
      #   print(f"{year} is Not a Leap year")
  # else:
  #   print(f"{year} is not a Leap year")
  return n_l

month=["jan","feb","march","april","may","june","july","aug","sept","oct","nov","dec"]
odd_days=[3,0,3,2,3,2,3,3,2,3,2,3]
Days=["Sunday","Monday","Tuesday","Wednensday","Thursday","Friday","Saturday"]
tot_odd_days=0
Day=int(input("Enter the Day in number: "))
while Day>31:
  print("Invalid Entry")
  Day=int(input("Enter the Day in number: "))
Month=input("Enter the month in words: ")
#Determine the month index
for element in month:
  if element[:2].lower()==Month[:2].lower():
    # print(element)
    element_index=month.index(element)+1
    break
for i in range(element_index-1):
  tot_odd_days+=odd_days[i]
tot_odd_days+=Day
# print(tot_odd_days)
Year=int(input("Enter the Year in number"))
for i in range(1,Year):
  n_l=number_leap(i)
tot_odd_days_year=n_l*2+(Year-1-n_l)*1
tot_odd=tot_odd_days+tot_odd_days_year
tot_odd_rem=tot_odd%7
if Year%4==0:
  if Year%100!=0:
    if element_index>2:
     print(f"{Day} {month[element_index-1]} {Year} is {Days[tot_odd_rem+1]}")
    else:
        print(f"{Day} {month[element_index-1]} {Year} is {Days[tot_odd_rem]}")
  else:
    if Year%400==0:
      if element_index>2:
          print(f"{Day} {month[element_index-1]} {Year} is {Days[tot_odd_rem+1]}")
      else:
          print(f"{Day} {month[element_index-1]} {Year} is {Days[tot_odd_rem]}")
    else:
        print(f"{Day} {month[element_index-1]} {Year} is {Days[tot_odd_rem]}")
else:
     print(f"{Day} {month[element_index-1]} {Year} is {Days[tot_odd_rem]}")

